# Generated by Django 4.2.5 on 2023-09-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storre', '0004_collection_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
